Add grouping for tasks in AzureDevOps pipeline
cake-contrib/Cake.BuildSystems.Module pull request #112
Opened 2021-12-29 07:41 UTC by JuergenRB

Closes #111

2021-12-29 11:51 UTC, nils-a commented
@JuergenRB Thanks for the PR!
May I ask, what was the reasoning for implementing an `IExecutionStrategy` instead of doing this in the existing `AzurePipelinesEngine`? 

The `TeamCityEngine` provides "groups" very similar to what was done here (see #101), but that is all based on the existing events provided by `ICakeEngine`. Am I missing something?

2021-12-29 14:54 UTC, JuergenRB commented
@nils-a 
My idea was not to have duplicate task titles in the log output. 
That's why I implemented it in ```IExecutionStrategy``` .

If you want, I can rebuild it so that it is solved in a consistent way.

2021-12-30 09:36 UTC, nils-a commented
@JuergenRB yes, having the functionality consistent would be good.

2022-01-03 21:32 UTC, JuergenRB commented
Changed
![image](https://user-images.githubusercontent.com/22403655/147982588-17da9a58-2503-45aa-bbbd-343c2a220780.png)

2022-01-03 22:10 UTC, nils-a requested changes
LGTM in general. One small change, though.

2022-01-03 22:10 UTC, nils-a commented on src/Cake.AzurePipelines.Module/Cake.AzurePipelines.Module.csproj
> +
Could you remove this, since the file no longer exists?

2022-01-04 08:11 UTC, nils-a approved these changes
LGTM

2022-01-04 08:12 UTC, merged